### ISSUE TITLE
Phantom items

### ISSUE THREAD

**Issue by lDoomerl** [TRCStudioDean/GlobalMarketPlus#20]
If you will try to take the item from the market with Shift + LMB the item will be added to the inventory for the client side. From the server side the item doesn't exist. But if the player will try to use it, for example Elytra - he can wear it and fly until he will try to unwear it. Then the item will disapear. 
Theoreticly it can cause some dupes, so need to check it. 

Tested on ver 1.2.7.0
Server Pufferfish 1.20.2

**Comment by lDoomerl** [comment]
I forgot to add that after Shift + LBM you need to press ESC very quickly

**Comment by TRCStudioDean** [comment]
This is due to the caching mechanism of the client, which has been the case since the earliest version of Minecraft. The client will not request correction again like the server. But what can be certain is that this is not a GMP issue, and if you are in a creative mode, you can even turn this item into reality.

**Comment by lDoomerl** [comment]
I see, thank you for your attention on this
